import { NextResponse } from 'next/server'
import { uploadToYouTube } from '@/lib/youtube-uploader'

export async function POST() {
  try {
    const videoPath = './public/output.mp4'
    const title = 'Latest Trending Topic - Automated Video'
    const description = 'This video was automatically generated by an AI agent to cover the latest trending topics.'

    const videoId = await uploadToYouTube(videoPath, title, description)

    return NextResponse.json({
      success: true,
      videoId
    })
  } catch (error) {
    console.error('Error uploading to YouTube:', error)
    return NextResponse.json({
      success: false,
      error: (error as Error).message
    }, { status: 500 })
  }
}
